wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1673688536.969571
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.15
      5: 0.13.7
      8:
      - 1
      - 3
      - 5
max_depth:
  desc: null
  value: 10
max_features:
  desc: null
  value: auto
max_leaf_nodes:
  desc: null
  value: null
min_samples_leaf:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 150
n_jobs:
  desc: null
  value: -1
random_state:
  desc: null
  value: 42
